//Задание 2. Если необходимо, исправьте данный код

    try {
        int d = 0;
        double catchedRes1 = intArray[8] / d;
        
        // В этой команде выполняется деление элемента массива intArray[8] на переменную d. 
        // Так как d равно 0, возникает исключение ArithmeticException, так как деление на ноль запрещено.

        System.out.println("catchedRes1 = " + catchedRes1);
     } catch (ArithmeticException e) {
        System.out.println("Catching exception: " + e);
        // Если возникнет исключение типа ArithmeticException, то переменная e будет содержать информацию об исключении.
        // Выводится на экран сообщение о том, что исключение было перехвачено, а также информация об исключении,
        // содержащаяся в переменной e.
     
//Код не требует исправлений
